/* Creacion de los triggers  para cada tabla*/ 

/*Triggers tabla persona*/

CREATE OR REPLACE FUNCTION validar_correo()
  RETURNS TRIGGER 
  LANGUAGE PLPGSQL
  AS
$$
BEGIN
	IF NEW.correo LIKE '%@%.%' THEN
		 RETURN NEW;
	END IF;

	RETURN NULL;
END;
$$

;;;

CREATE TRIGGER TG_CHECK_EMAIL_ON_INSERT BEFORE INSERT ON PERSONA FOR EACH ROW EXECUTE FUNCTION validar_correo();
CREATE TRIGGER TG_CHECK_EMAIL_ON_UPDATE BEFORE UPDATE ON PERSONA FOR EACH ROW EXECUTE FUNCTION validar_correo();
